### PR TITLE
Updates to new users information.

### PR DESCRIPTION
**Pull request by somiaj**
First remove the testimonials page, and add a new why use fvwm page which combines the various reasons why people choose to use fvwm. This seems more useful and a better idea than having random testimonials from fvwm developers. I also finally add the BlankConfig page I have been meaning to for way to long, and moved and updated the WindowManager page. This also felt like a NewToFvwm type info (which did have a small blurb on the why fvwm slant which was extended here).

@rasatpc Does this seem to have the intent you had for wanting to add more testimonials. Any suggestions?

### CODE REVIEW

**Comment by rasatpc** [comment]
When I was copying the testimonials, I was visualizing the interests and motives of the fvwm users. Where would one go from there? What pages to improve or add? For example:

_I like fvwm’s approach - no defaults and everything is up to the user, and I can hardly imagine myself using anything else. Even with my lame coding style, fvwm meets my needs perfectly._
https://www.fvwm.org/Wiki/Modules/

_“Hey, this thing is actually quite configurable”, so I started to read manpages._
https://www.fvwm.org/Wiki/Config/

_How such a minimal WM, many times underrated, can incorporate the most advanced graphical features and functions._
Link to a page of advanced features and functionalities.

_I almost changed my mind instantly until someone gave me a nice .fvwm2rc to play with._
https://fvwm-themes.sourceforge.net (links to selected themes or configs with short descriptions of what they do.)

**Comment by ThomasAdam** [comment]
Hi @rasatpc 

I'm not sure that your example is the intended audience of those who are already reading this wiki.  I think I'm going to merge this -- and please -- if you have any other content you'd like for consideration, open more PRs.

**Comment by rasatpc** [comment]
Sorry, I only replied to @somiaj question. Didn't see the page.
https://www.fvwm.org/Wiki/NewToFvwm/WhyFvwm/

The text creates a monotonous environment. The information is good but the layout does not inspire anyone to read it. I will take a look at the layout.

**Comment by rasatpc** [comment]
Here is a sample page layout.
https://rasatpc.net/screenshot/wiki/why-fvwm.png

**Comment by somiaj** [comment]
I don't agree with you logic that no one would want to read a list of information, as I prefer when sites just list the info they want to share. Also if someone isn't willing to read a list of information like that, they probably are less willing to want to use fvwm. That being said, I'm not against your changes, I just think your stance is a bit off putting.

As for your suggested changes, I'm mostly neutral on. If you feel this will improve the page, please make a PR.

**Comment by somiaj** [comment]
@rasatpc if you are going to move forward with this, you should use FvwmWindows to highlight the blocks of text, not quotes. https://www.fvwm.org/Wiki/FvwmWeb/FvwmWindow/

**Comment by rasatpc** [comment]
@somiaj , sorry for my irrational expression. I had a rough teacher when learning newspaper design (layout). :)
Thanks for the FvwmWindow link. Do you have a good link for Jekyll markdown examples?

The new layout example for WhyFvwm is on PR.

**Pull request merged**
