### PR TITLE
New testimonials

### PR DESCRIPTION
**Pull request by rasatpc**
9 new testimonials from different fondness.

### CODE REVIEW

**Comment by ThomasAdam** [comment]
Hi @rasatpc 

Whilst I appreciate the sentiment, I am not sure this is worthwhile.  Most users you've listed there might not be using FVWM any more, and some of them mention things like FvwmThemes which isn't used at all any more.

The one thing fvwm doesn't need is more IMO.

**Comment by rasatpc** [comment]
These testimonials are not sentimental but carry a message to NEW users who don't know the members who post them. It encourages reading manpages, doesn't require one to be a coding expert, Fvwm is active and alive, the newness of "Virtual Desktop Manager", minimal with endless configure, available configs to start with, etc.

Good references when promoting Fvwm. Anything outdated (FvwmThemes) can be removed or replaced with new ones.
If there are too many, we can reduce them.

**Comment by ThomasAdam** [comment]
I understand that -- and you've clearly went looking for those which is nice.  But you really should have read them first, and for things like fvwm-themes, not included them in the first place.

As it stands, I'm personally against including these testimonials, they're a rather dated means to garner new users' interest.

**Comment by somiaj** [comment]
The testimonials page could probably be removed, an antiquated idea and not really what a wiki is for. People primarily come to the wiki (or even the fvwm.org webpage) who want to know more about how to configure fvwm.

Also the testimonials that are currently on the wiki were written and contributed by the author. I don't feel comfortable adding comments of users scrubbed from other sources.

Thanks for your enthusiasm to want to make the wiki better and help show new users what fvwm is about, but I don't think this approach would add to that in the long run.

**Comment by rasatpc** [comment]
I am comming from a wiki background, starting the Arch Linux wiki (2004). A collaborative platform where users contribute, edit, and delete. The result is wonderful. Here we are concluding testimonials are an "antiquated idea". It can be removed, wiki usually doesn't include testimonials. Or move it to the Fvwm web section.

**Comment by ThomasAdam** [comment]
Closing this, per the comments.  We should probably archive the existing testimonial pages.

**Comment by somiaj** [comment]
Agree, we should remove the testimonial page. The only reason I haven't yet, was I was thinking we could take the intent of the testimonials, which is reasons why people would want to use fvwm, and create a new page along the lines of `Why use fvwm?`. The page could help new users by stating the reasons people like to use fvwm, along with some reasons why not, and see this as a replacement of the testimonial page.

**Comment by ThomasAdam** [comment]
> Agree, we should remove the testimonial page. The only reason I haven't yet, was I was thinking we could take the intent of the testimonials, which is reasons why people would want to use fvwm, and create a new page along the lines of `Why use fvwm?`. The page could help new users by stating the reasons people like to use fvwm, along with some reasons why not, and see this as a replacement of the testimonial page.

@somiaj -- that sounds like a great idea to me.

**Pull request closed without merging**
