### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by andibachmann**
Fix string equality: Correct test is [ "$[DIR]" = "Prev" ]

### CODE REVIEW

**Comment by ThomasAdam** [comment]
Hi @andibachmann 

Thanks for the diff.  Agreed -- although `ExecUseShell` will change this behaviour.

Is there any reason your pull request doesn't look like this?

```
diff --git a/Wiki/CookBook/AltTab/index.md b/Wiki/CookBook/AltTab/index.md
index afe4f8b..4510dfb 100644
--- a/Wiki/CookBook/AltTab/index.md
+++ b/Wiki/CookBook/AltTab/index.md
@@ -80,7 +80,7 @@ AddToFunc FocusRaiseAndStuff
 AddToFunc SwitchWindow
 + I $[DIR] (CurrentPage, !Iconic, !Sticky) FocusRaiseAndStuff
 + I Deschedule 134000
-+ I PipeRead `[ "$[DIR]" == "Prev" ] && \
++ I PipeRead `[ "$[DIR]" = "Prev" ] && \
     echo 'SetEnv NDIR Next' || \
     echo 'SetEnv NDIR Prev'`
 + I Schedule 700 134000 SetEnv DIR $[NDIR]
```

I don't see the need for any of the other changes in your pull-request.

**Comment by andibachmann** [comment]
Hi Thomas

I was not sure, how this function works on other systems having another
implementation of /bin/sh. I therefore thought it'd be 'nicer' to add the
'Troubleshooting' section. Just fixing the '==' is perfectly fine with me.
:-)


btw, in the official docu there is at some other place very much the same
snippet for the Alt-Tab problem using 'InfoStoreAdd' instead of 'SetEnv'.

Regards
Andi


-- 
andi bachmann, bienenstrassse 13, 8004 zürich
tel:+41 43 243 35 64 mobile: +41 76 329 96 13

**Comment by somiaj** [comment]
You should be able to assume everyone's shell is POSIX standard. Just update the syntax to use POSIX standards instead of bash (or some other shell's) specific syntax.

**Comment by somiaj** [comment]
It appears that the single `=` sign is POSIX. Basically dash (/bin/sh on Debian based systems) is a minimal shell that implements POSIX standards. If it runs in dash, it should run in any POSIX shell. There is no reason to support non POSIX shells.

**Comment by somiaj** [comment]
> btw, in the official docu there is at some other place very much the same snippet for the Alt-Tab problem using 'InfoStoreAdd' instead of 'SetEnv'.

Using `InfoStoreAdd` is probably better here, as this setting doesn't need to be a part of the environment. This should probably be updated to use that, and not use a shell. This was probably written before `InfoStoreAdd` was added.  I would update the function to be something like this:

```
InfoStoreAdd TabDir Next

AddToFunc SwitchWindow
+ I $[infostore.TabDir] (CurrentPage, !Iconic, !Sticky) FocusRaiseAndStuff
+ I Deschedule 134000
+ I Test (EnvMatch infostore.TabDir Next) InfoStoreAdd TabNDir Prev
+ I TestRc (NoMatch) InfoStoreAdd TabNDir Next
+ I Schedule 700 134000 InfoStoreAdd TabDir $[infostore.TabNDir]
```

Note, I haven't actually tested this, so it may need some tweaks.

**Comment by ThomasAdam** [comment]
Hey @andibachmann 

Thanks for this -- we've taken the essence of what was being discussed here, and added those to PR #28 instead.  I've attributed your original request in the commit message there.

I'm therefore closing this.

**Pull request closed without merging**
