### PR TITLE
FvwmRearrange: add column examples

### PR DESCRIPTION
**Pull request by ThomasAdam**
Add an example showing how FvwmRearrange can be used to put windows into columns.

### CODE REVIEW

**Comment by ThomasAdam** [comment]
@rasatpc 

Here you go.

**Comment by rasatpc** [comment]
This is what I am considering as a wiki. The person contributing to a page doesn't deal with GitHub technicalities.  The GitHub repo owner does the edits and addons. When ready, make a new PR and push it to the main. Let's do this from now onward. This may also encourage more users to contribute.

The page is ok and ready to publish.

**Comment by ThomasAdam** [comment]
@rasatpc 

Umm, no. That's certainly not going to happen. The way it works now is how it is. 

This project is tiny, and there's not the resources to put to offloading someone's lack of git knowledge.

**Comment by somiaj** [comment]
Git is a common tool used today, it is worth learning it. I do understand your sentiment that it is a layer that makes editing a 'wiki' a bit more work, but creating another workflow just for the wiki is not something fvwm has the bandwidth for. fvwm.org is a static website, that means it has no forms, dynamic generation, or method to create a user interface to edit the wiki and also have any edits reviewed. Currently all of fvwm code and website is on github, which provides all the tools share the code with anyone who wants it, and allows anyone to make forks and submit pull requests to modify the code, which then gets reviewed. The review process is important because once the information is in the wiki, it will probably be there for ages before someone wants to edit it again, so let's ensure we get the best quality we can for any changes.

Just like you have learned fvwm, you can also learn git, and the basics aren't too bad once you get use to a few of its quirks. I suggest you use `git commit --amend` instead of `git commit` when making any modifications to one of your commits. This will just update the previous commit, and let you edit the commit message (though you can keep it the same if it needs no edits).

**Comment by somiaj** [comment]
@rasatpc Also, thanks for your contributions, it will become easier as you get more familiar with the tools.

**Comment by rasatpc** [comment]
The basic one has to learn from somewhere Instead of spending hours in Google searches or reading instructions that are not designed for a newbie, every Wikipedia/MediaWiki project has a How-to-do page.
https://www.mediawiki.org/wiki/Help:Editing_pages

If there is not yet in Fvwm Web, I am suggesting, that we add to Wiki/FvwmWeb/. Currently, it mentions "To contribute to the FvwmWiki (or website) submit pull requests using GitHub". Details on how to make PR is missing.

I will get the details from Stackoverflow, the basics of PR with a few simple examples.

**Comment by ThomasAdam** [comment]
@rasatpc 

I'm not going to want pages in the wiki or elsewhere on fvwm.org to mention how to use git.  That may seem harsh, but the reality is that there's plenty of sites dedicated to that, and that's not a subject matter for fvwm at all.

What *is* important though is the way PRs might want to be constructed.   This is documented for fvwm3, and the mechanics of that applies just as well to the website.  See:

https://github.com/fvwmorg/fvwm3/blob/main/dev-docs/DEVELOPERS.md#branch-workflows--submitting-code-changes

The only difference here though, is the default branch in fvwmorg.github.io is `master` and not `main` -- but that's just a semantic difference when it comes to following those instructions.

So if you wanted to do anything, it might be to make a page which references that link above.

As for contributing to the wiki, I'm not sure what information you feel is lacking, but the FvwmWeb page you mentioned reads very well to me -- and mentions all manner of useful things to do with styling, themes, etc.

**Comment by rasatpc** [comment]
If I had seen this fvwm3/dev-docs/DEVELOPERS.md page, most likely we would not have had this discussion. I am not the only one with this question.

There are no questions about contributing to the wiki. The instructions are good, and easy to find.

**Pull request merged**
