### PR TITLE
4Btm Decor Example

### PR DESCRIPTION
**Pull request by rasatpc**
For FvwmWiki -- This example will configure your window with a simple and modern look. Either with a flat color title bar or with an image. The bar has 4 buttons on the right side and one on the left side. The 4th button is assigned to a specific function or your favorite application.

### CODE REVIEW

**Comment by ThomasAdam** [comment]
@rasatpc 

It still seems to me that these two commits need squashing together?

**Comment by somiaj** [comment]
@rasatpc thanks for implementing the suggested changes. To squish the two commits you need to:

1) Run `git rebase -i HEAD~2`
2) Using the editor that opens up change `pick` to `squash` on the second commit.
3) Save and exit the editor (this depends on what editor you use)
4) Force push the changes back to github, `git push -f`

One note for future use, you should create a branch and not just make modifications to the master branch for PRs. You may want to look up how to do that, but for this PR don't worry about it.

**Comment by rasatpc** [comment]
git rebase -i HEAD~2 opens the nano.
```
pick 82503f8 4Btm Decor
pick 9aa0aed 4Btm Decor

# Rebase 8e99219..9aa0aed onto 8e99219 (2 commands)
#
# Commands:
```
To be sure, is this edit correct?
```
pick 82503f8 4Btm Decor
squash 9aa0aed 4Btm Deco
```
About the branch for new PR. Should new Decor, CookBook or Tips have its own PR or can one PR include many new items?

**Comment by somiaj** [comment]
You followed the instructions, but until you force push the changes to this branch, we can't see you squished the commits.

Splitting up your suggested changes into individual branches (don't use the master branch) and making a PR for each one will make reviewing easier, and allow any edits to focus on a single page at a time. But depending on what you are changing, you can combine multiple new pages in a single PR.

**Comment by rasatpc** [comment]
It is done. If any minor edits on any page, is it better to create an issue instead of PR?

**Comment by somiaj** [comment]
Create a PR with any edits/fixes, unless you are unsure the best way to fix. In that case raise an issue

**Pull request merged**
