### PR TITLE
4Btm Decor

### PR DESCRIPTION
**Pull request by rasatpc**
This is for the FvwmWiki. A decor example that configures the window with a simple and modern look. Either with a flat color title bar or with an image. The bar has 4 buttons on the right side and one on the left side. The 4th button is assigned to a specific function or application.

Later, this decor page will include links to related functions and features that give more functionalities to this decor.

### CODE REVIEW

**Comment by somiaj** [comment]
Overall looks good, though there are a few things I would like you to change.

First, lets not use Thunar in screenshots. I tried to make the screenshots generic, use a terminal and manually set the `-title` of the window to be the decor name, or use FvwmConsole. No need for the screenshots to show applications like Thunar or let users know what directory you are in just to show the decor.

Second, don't add your custom `QTile` function to the bindings. Instead just use something like `MyCustomFunction`, something that is obviously a place holder (yes your comment does that but I would remove the comment). In the end Decors should be about the look and not the functionality, and `QTile` might confuse users who think it is a internal fvwm command.

Last, I don't like your idea of linking this to additional functionality. A decor should focus only on the looks. You can add `QTile` function to the `CookBook` (or other features) as an independent page, but a decor should be about the looks.

**Review by somiaj — CHANGES_REQUESTED** [review]
Changes list above.

**Comment by somiaj** [comment]
Also last, lets squish all the commits into a single commit, we don't need your 'Test' commits polluting the commit history.

**Comment by somiaj** [comment]
Please keep questions about this PR here, no need to message me elsewhere.

> How to remove the Test commit or any commit in general? On Google search, it looks quite complex.
> How to squish all commits into a single commit?

You can either just start over, and copy over your changes and create a new commit, or squish the commits. You have 9 commits, so something like `git rebase -i HEAD~9` will give you an option to rebase the commits, you should drop the first two test commits and then squish the other ones. The editor that opens up will tell you the keyword to use for each commit to modify it.

If you want to make a small edit to your last commit, use `git commit --amend` to edit the current commit instead of adding a new one.

>  You asked me to edit a few places. After editing on [my GitHub site](https://github.com/rasatpc/fvwmorg.github.io), do I have to create one new pull request?

Don't create a new PR, best to have everything in a single one. Once you do these changes, your local branch and the remote one will differ, and you will have to force push the changes to deal with this, `git push -f`. Once you update your local fork you are using in this PR, all changes will be reflected here.

Also in the future best to create a branch for each PR you are doing, but in this case I wouldn't worry about that.

**Comment by rasatpc** [comment]
I need to start over. When I moved one commit on my local, it caused 8 news commits on GitHub, now total 17. If I delete my fork repo and create one new, is it better to first remove this pull request?

**Comment by somiaj** [comment]
Since this PR is coming from your `master` branch of your fork, any changes to that branch will be seen here. What you have done is fixable, seems you need a bit more familiarity with git.

**Pull request closed without merging**
